import { afterEach, describe, expect, it } from "vitest";
import pg from "pg";

import { affectedRows, isPostgresUrl, isUniqueViolation, openKnowledgeDb } from "./client.js";
import { migratePg } from "./migrate-pg.js";
import { dropSchema, TEST_DB_URL, TEST_DIALECT, uniqueSchemaName } from "../test-utils/db.js";

describe("dialect selection", () => {
  it("postgres:// and postgresql:// select Postgres, anything else does not", () => {
    expect(isPostgresUrl("postgres://u:p@h:5432/db")).toBe(true);
    expect(isPostgresUrl("postgresql://h/db")).toBe(true);
    expect(isPostgresUrl("")).toBe(false);
    expect(isPostgresUrl(undefined)).toBe(false);
    expect(isPostgresUrl("mysql://h/db")).toBe(false);
  });

  it("no URL keeps upstream SQLite", async () => {
    const kdb = await openKnowledgeDb({ path: ":memory:" });
    expect(kdb.dialect).toBe("sqlite");
    await kdb.close();
  });

  it("a non-postgres URL is rejected instead of silently falling back to SQLite", async () => {
    await expect(openKnowledgeDb({ url: "mysql://h/db", path: ":memory:" })).rejects.toThrow(/postgres/);
  });

  it("affectedRows / isUniqueViolation understand both drivers", () => {
    expect(affectedRows({ changes: 2 })).toBe(2);
    expect(affectedRows({ rowCount: 3 })).toBe(3);
    expect(affectedRows(undefined)).toBe(0);
    expect(isUniqueViolation(new Error("UNIQUE constraint failed: t.id"))).toBe(true);
    expect(isUniqueViolation(Object.assign(new Error("Failed query"), { cause: { code: "23505" } }))).toBe(true);
    expect(isUniqueViolation(new Error("boom"))).toBe(false);
  });
});

describe.runIf(TEST_DIALECT === "postgres")("Postgres migrations", () => {
  const schemas: string[] = [];
  afterEach(async () => {
    for (const s of schemas.splice(0)) await dropSchema(TEST_DB_URL, s);
  });

  async function columns(pool: pg.Pool, schema: string, table: string): Promise<string[]> {
    const res = await pool.query(
      "SELECT column_name FROM information_schema.columns WHERE table_schema = $1 AND table_name = $2",
      [schema, table],
    );
    return res.rows.map((r: { column_name: string }) => r.column_name);
  }

  it("are idempotent and create every table in the requested schema", async () => {
    const schema = uniqueSchemaName();
    schemas.push(schema);
    const pool = new pg.Pool({ connectionString: TEST_DB_URL, max: 2 });
    try {
      await migratePg(pool, schema);
      await migratePg(pool, schema);
      const res = await pool.query(
        "SELECT table_name FROM information_schema.tables WHERE table_schema = $1 ORDER BY table_name",
        [schema],
      );
      expect(res.rows.map((r: { table_name: string }) => r.table_name)).toEqual([
        "knowledge_code_graph",
        "knowledge_code_graph_audit",
        "knowledge_git_credential",
        "knowledge_git_credential_audit",
        "knowledge_wiki",
        "knowledge_wiki_audit",
        "llm_binding",
      ]);
    } finally {
      await pool.end();
    }
  });

  it("adds late columns to a pre-existing table", async () => {
    const schema = uniqueSchemaName();
    schemas.push(schema);
    const pool = new pg.Pool({ connectionString: TEST_DB_URL, max: 2 });
    try {
      await pool.query(`CREATE SCHEMA "${schema}"`);
      await pool.query(
        `CREATE TABLE "${schema}".knowledge_wiki_audit (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
           wiki_id TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 0, action TEXT NOT NULL,
           user_id TEXT, agent_id TEXT, detail TEXT, created_at TEXT NOT NULL)`,
      );
      await migratePg(pool, schema);
      expect(await columns(pool, schema, "knowledge_wiki_audit")).toContain("service_id");
    } finally {
      await pool.end();
    }
  });

  it("concurrent migrations of one schema do not race", async () => {
    const schema = uniqueSchemaName();
    schemas.push(schema);
    const pool = new pg.Pool({ connectionString: TEST_DB_URL, max: 4 });
    try {
      await Promise.all([migratePg(pool, schema), migratePg(pool, schema), migratePg(pool, schema)]);
      expect(await columns(pool, schema, "knowledge_code_graph")).toContain("credential_id");
    } finally {
      await pool.end();
    }
  });

  it("openKnowledgeDb rejects an unsafe schema name", async () => {
    await expect(openKnowledgeDb({ url: TEST_DB_URL, path: "", schema: 'x"; DROP' })).rejects.toThrow(/SCHEMA/);
  });
});
