/**
 * Idempotent Postgres DDL for the metadata tables — the counterpart of `migrate()` in client.ts.
 *
 * Runs in one transaction under an advisory lock, so replicas starting together do not race on
 * CREATE ... IF NOT EXISTS (which is not concurrency-safe in Postgres). Column additions that the
 * SQLite side does via addColumnIfMissing are `ADD COLUMN IF NOT EXISTS` here.
 */

import type { Pool } from "pg";

const DDL = `
  CREATE TABLE IF NOT EXISTS knowledge_code_graph (
    code_graph_id   TEXT PRIMARY KEY,
    service_id      TEXT NOT NULL,
    team_id         TEXT NOT NULL,
    repo_name       TEXT NOT NULL DEFAULT '',
    repo_url        TEXT NOT NULL,
    branch          TEXT NOT NULL,
    commit_hash     TEXT,
    owner_user_id   TEXT,
    user_id         TEXT,
    agent_id        TEXT,
    task_id         TEXT,
    visibility      TEXT NOT NULL DEFAULT 'team',
    status          TEXT NOT NULL DEFAULT 'pending',
    internal_status TEXT,
    sync_error      TEXT,
    stats_json      TEXT,
    version         INTEGER NOT NULL DEFAULT 0,
    last_sync_at    TEXT,
    created_at      TEXT NOT NULL,
    updated_at      TEXT NOT NULL,
    deleted_at      TEXT
  );
  ALTER TABLE knowledge_code_graph ADD COLUMN IF NOT EXISTS service_url TEXT;
  ALTER TABLE knowledge_code_graph ADD COLUMN IF NOT EXISTS summary TEXT;
  ALTER TABLE knowledge_code_graph ADD COLUMN IF NOT EXISTS credential_id TEXT;
  CREATE UNIQUE INDEX IF NOT EXISTS idx_kcg_team_repo_branch
    ON knowledge_code_graph(service_id, team_id, repo_url, branch)
    WHERE deleted_at IS NULL;
  CREATE INDEX IF NOT EXISTS idx_kcg_team_status
    ON knowledge_code_graph(service_id, team_id, status);

  CREATE TABLE IF NOT EXISTS knowledge_wiki (
    wiki_id         TEXT PRIMARY KEY,
    service_id      TEXT NOT NULL,
    team_id         TEXT NOT NULL,
    name            TEXT NOT NULL,
    source_type     TEXT,
    source_url      TEXT,
    owner_user_id   TEXT,
    user_id         TEXT,
    agent_id        TEXT,
    task_id         TEXT,
    visibility      TEXT NOT NULL DEFAULT 'team',
    status          TEXT NOT NULL DEFAULT 'draft',
    internal_status TEXT,
    sync_error      TEXT,
    page_count      INTEGER,
    version         INTEGER NOT NULL DEFAULT 0,
    last_sync_at    TEXT,
    created_at      TEXT NOT NULL,
    updated_at      TEXT NOT NULL,
    deleted_at      TEXT
  );
  ALTER TABLE knowledge_wiki ADD COLUMN IF NOT EXISTS service_url TEXT;
  ALTER TABLE knowledge_wiki ADD COLUMN IF NOT EXISTS summary TEXT;
  CREATE UNIQUE INDEX IF NOT EXISTS idx_kwiki_team_name
    ON knowledge_wiki(service_id, team_id, name)
    WHERE deleted_at IS NULL;
  CREATE INDEX IF NOT EXISTS idx_kwiki_team_status
    ON knowledge_wiki(service_id, team_id, status);

  CREATE TABLE IF NOT EXISTS knowledge_wiki_audit (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wiki_id    TEXT NOT NULL,
    version    INTEGER NOT NULL DEFAULT 0,
    action     TEXT NOT NULL,
    user_id    TEXT,
    agent_id   TEXT,
    detail     TEXT,
    created_at TEXT NOT NULL
  );
  ALTER TABLE knowledge_wiki_audit ADD COLUMN IF NOT EXISTS service_id TEXT;
  CREATE INDEX IF NOT EXISTS idx_kwa_wiki_version
    ON knowledge_wiki_audit(wiki_id, version DESC);

  CREATE TABLE IF NOT EXISTS knowledge_code_graph_audit (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_graph_id TEXT NOT NULL,
    version       INTEGER NOT NULL DEFAULT 0,
    action        TEXT NOT NULL,
    user_id       TEXT,
    agent_id      TEXT,
    detail        TEXT,
    created_at    TEXT NOT NULL
  );
  ALTER TABLE knowledge_code_graph_audit ADD COLUMN IF NOT EXISTS service_id TEXT;
  CREATE INDEX IF NOT EXISTS idx_kcga_cg_version
    ON knowledge_code_graph_audit(code_graph_id, version DESC);

  CREATE TABLE IF NOT EXISTS llm_binding (
    service_id     TEXT PRIMARY KEY,
    mode           TEXT NOT NULL DEFAULT 'proxy',
    proxy_base_url TEXT,
    api_key        TEXT,
    model          TEXT,
    base_url       TEXT,
    enabled        INTEGER NOT NULL DEFAULT 1,
    updated_at     TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS knowledge_git_credential (
    credential_id TEXT PRIMARY KEY,
    service_id    TEXT NOT NULL,
    team_id       TEXT NOT NULL,
    name          TEXT NOT NULL,
    kind          TEXT NOT NULL,
    host          TEXT NOT NULL,
    username      TEXT,
    secret_enc    TEXT NOT NULL,
    fingerprint   TEXT NOT NULL,
    created_by    TEXT,
    created_at    TEXT NOT NULL,
    updated_at    TEXT NOT NULL,
    deleted_at    TEXT
  );
  CREATE UNIQUE INDEX IF NOT EXISTS idx_kgcred_team_name
    ON knowledge_git_credential(service_id, team_id, name)
    WHERE deleted_at IS NULL;
  CREATE INDEX IF NOT EXISTS idx_kgcred_team_host
    ON knowledge_git_credential(service_id, team_id, host);

  CREATE TABLE IF NOT EXISTS knowledge_git_credential_audit (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credential_id TEXT NOT NULL,
    service_id    TEXT,
    action        TEXT NOT NULL,
    user_id       TEXT,
    detail        TEXT,
    created_at    TEXT NOT NULL
  );
  CREATE INDEX IF NOT EXISTS idx_kgca_cred
    ON knowledge_git_credential_audit(credential_id, id DESC);

  -- Per-wiki search index (the SQLite side keeps one index.db per wiki; see engines/wiki/index-store-pg.ts).
  -- page_meta + wiki_fts in one row: title_tok/content_tok hold the same pre-tokenised text SQLite feeds
  -- FTS5; the generated tsvector weights the title A and the content D (ts_rank_cd weights 1.0 / 0.2 = 5:1).
  CREATE TABLE IF NOT EXISTS knowledge_wiki_page (
    wiki_id     TEXT NOT NULL,
    page_id     TEXT NOT NULL,
    title       TEXT,
    type        TEXT,
    rel_path    TEXT,
    snippet     TEXT,
    title_tok   TEXT NOT NULL DEFAULT '',
    content_tok TEXT NOT NULL DEFAULT '',
    fts         TSVECTOR GENERATED ALWAYS AS (
                  setweight(to_tsvector('simple'::regconfig, title_tok), 'A') ||
                  setweight(to_tsvector('simple'::regconfig, content_tok), 'D')
                ) STORED,
    PRIMARY KEY (wiki_id, page_id)
  );
  CREATE INDEX IF NOT EXISTS idx_kwp_fts ON knowledge_wiki_page USING GIN (fts);

  CREATE TABLE IF NOT EXISTS knowledge_wiki_edge (
    wiki_id   TEXT NOT NULL,
    source_id TEXT NOT NULL,
    target_id TEXT NOT NULL,
    PRIMARY KEY (wiki_id, source_id, target_id)
  );

  CREATE TABLE IF NOT EXISTS knowledge_wiki_source (
    wiki_id          TEXT NOT NULL,
    filename         TEXT NOT NULL,
    sha256           TEXT NOT NULL,
    size             INTEGER NOT NULL,
    status           TEXT NOT NULL,
    created_at       TEXT NOT NULL,
    updated_at       TEXT NOT NULL,
    last_modified_by TEXT,
    ingested_at      TEXT,
    ingest_error     TEXT,
    PRIMARY KEY (wiki_id, filename)
  );
`;

/** Validated identifier: the schema name is interpolated into DDL, so no quoting games. */
export const PG_SCHEMA_RE = /^[a-z_][a-z0-9_]{0,62}$/;

export async function migratePg(pool: Pool, schema?: string): Promise<void> {
  const client = await pool.connect();
  try {
    await client.query("BEGIN");
    await client.query("SELECT pg_advisory_xact_lock(hashtext($1))", [`tdai-knowledge-migrate:${schema ?? ""}`]);
    if (schema) {
      if (!PG_SCHEMA_RE.test(schema)) throw new Error(`invalid Postgres schema name: ${schema}`);
      await client.query(`CREATE SCHEMA IF NOT EXISTS "${schema}"`);
      await client.query(`SET LOCAL search_path TO "${schema}"`);
    }
    await client.query(DDL);
    await client.query("COMMIT");
  } catch (err) {
    await client.query("ROLLBACK").catch(() => undefined);
    throw err;
  } finally {
    client.release();
  }
}
